### ISSUE TITLE
feat: filament management

### ISSUE THREAD

**Issue by jichengzhi** [monash-automation/mes-printing-server#48]
Need APIs to manage filaments in the lab. For now, each step is done manually. for example:

- user add record (PLA, yellow, 1m) after taking certain amount of filament
- admin check records and current inventory
- admin add new filaments to inventory

**Comment by jichengzhi** [comment]
# Manually Logging from Keenan:

## Filament Stock
<img width="1466" alt="Screenshot 2024-04-08 at 15 00 48" src="https://github.com/monash-automation/mes-printing-server/assets/28958099/1da20901-a7eb-46cc-b202-176382e208b8">

## Filament Loading/Unloading
<img width="1466" alt="Screenshot 2024-04-08 at 15 01 04" src="https://github.com/monash-automation/mes-printing-server/assets/28958099/d022346f-839a-4e85-aea3-9c68f18c48f1">

## Print Jobs
<img width="1466" alt="Screenshot 2024-04-08 at 15 01 19" src="https://github.com/monash-automation/mes-printing-server/assets/28958099/404a4125-36c4-419d-a317-5ca926209083">

**Comment by shiki65536** [comment]
#### Update:
- Created branch filament to address the issue

#### Questions:
- Not sure the following feature is about "Update" or "Create" another table to record.
- Is filament transaction needed?

#### Issue:
- Struggling in writing test_filament.py

**Comment by jichengzhi** [comment]
> #### Update:
> * Created branch filament to address the issue
> 
> #### Questions:
> * Not sure the following feature is about "Update" or "Create" another table to record.
> * Is filament transaction needed?
> 
> #### Issue:
> * Struggling in writing test_filament.py

For future commits, submit a PR instead of pushing a new branch, otherwise I cannot write reviews to your code

**Comment by shiki65536** [comment]
> > #### Update:
> > 
> > * Created branch filament to address the issue
> > 
> > #### Questions:
> > 
> > * Not sure the following feature is about "Update" or "Create" another table to record.
> > * Is filament transaction needed?
> > 
> > #### Issue:
> > 
> > * Struggling in writing test_filament.py
> 
> For future commits, submit a PR instead of pushing a new branch, otherwise I cannot write reviews to your code.
> 
> An example is #33.

I am so sorry, totally forgot I should fork then PR.
I've forked and updated the code in my repo. We can delete the branch here.
Apologize again for how careless I am.

**Comment by jichengzhi** [comment]
Close due to inactivity for more than 2 weeks
